drop database SistemaInventarios;

CREATE DATABASE SistemaInventarios;

USE SistemaInventarios;

CREATE TABLE Producto (
	id INT IDENTITY(1,1) PRIMARY KEY,
	nombre TEXT NOT NULL,
	precio FLOAT NOT NULL,
	unidadMedida TEXT,
	tipo TEXT,
);

--Pagina mermas--
CREATE TABLE MermasMalEstado (
	idMerma INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto	INT NOT NULL,
	cantidad FLOAT NOT NULL,
	CONSTRAINT FK_ProductosMalEstado_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
); 

CREATE TABLE MermasCortes (
	idMerma INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto	INT NOT NULL,
	cantidad FLOAT NOT NULL,
	CONSTRAINT FK_MermasCortes_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
); 

CREATE TABLE Gasto (
	idGasto INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	idProducto INT NOT NULL,
	Cantidad FLOAT NOT NULL,
	CONSTRAINT FK_Gasto_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
);

--SELECT Producto.Nombre, Producto.Precio, ProductosMalEstado.Cantidad, ProductosMalEstado.Cantidad * Producto.Precio AS Total
--FROM ProductosMalEstado INNER JOIN producto 
--ON Producto.ID = ProductosMalEstado.IDProducto--

CREATE TABLE FiestaChicas (
	idFiestaChicas INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto INT NOT NULL,
	Cantidad FLOAT NOT NULL,
	CONSTRAINT FK_FiestaChicas_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
);

CREATE TABLE GastoComidaPersonal (
	idComidaPersonal INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto INT NOT NULL,
	KilosXMes FLOAT NOT NULL,
	CONSTRAINT FK_GastoComidaPersonal_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
);

--Nuevo cambio Mermas--

CREATE TABLE PlatosDevueltos (
	idPlatosDevueltos INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NombreProducto INT NOT NULL,
	Cantidad FLOAT NOT NULL,
	Precio FLOAT NOT NULL,
);



--Pagina Verduras--

CREATE TABLE ReporteGastoVerdura (
	idReporteVerduras INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto INT NOT NULL,
	CantidadGastoXDia FLOAT NOT NULL,
	dia INT NOT NULL,
	CONSTRAINT FK_ReporteGastoVerdura_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
);

--Pagina Interno--

CREATE TABLE LicorConsumoInterno (
	idLicor INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	tipo FLOAT NOT NULL,
	nombre TEXT NOT NULL,
	precio FLOAT NOT NULL,
);

CREATE TABLE ConsumoInternoLicRest (
	idPlato INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idLicor INT NOT NULL,
	medida FLOAT NOT NULL,
	cantidad FLOAT NOT NULL,
	CONSTRAINT FK_ConsumoInternoLicRest_LicorConsumoInterno FOREIGN KEY (idLicor) REFERENCES LicorConsumoInterno(idLicor),
);

CREATE TABLE ConsumoInternoLicTiki (
	idPlato INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idLicor INT NOT NULL,
	medida FLOAT NOT NULL,
	cantidad FLOAT NOT NULL,
	CONSTRAINT FK_ConsumoInternoLicTiki_LicorConsumoInterno FOREIGN KEY (idLicor) REFERENCES LicorConsumoInterno(idLicor),
);

CREATE TABLE Plato (
	idPlato INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	nombre TEXT NOT NULL,
	cantidad FLOAT NOT NULL,
	gramaje FLOAT NOT NULL,
);

CREATE TABLE ConsumoInterno ( 
	idConsumoInterno INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	nombre TEXT NOT NULL,
	GRM FLOAT NOT NULL,
	costo FLOAT NOT NULL,
);



--Pagina Pedidos--

CREATE TABLE Pedido (
	idPedido INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idProducto INT NOT NULL,
	dia TEXT NOT NULL, --(1-7, 8-14, 15-21, 22-28, 29-31)--
	CantidadPedido FLOAT NOT NULL,
	invInicial FLOAT NOT NULL,
	invFinal FLOAT NOT NULL,
	CONSTRAINT FK_Pedido_Producto FOREIGN KEY (idProducto) REFERENCES Producto(id),
); 

--Pagina ventas--
--la tabla sobrante debe ser para tiki y restaurante, qué se hace?
--la fecha debe ser en número y no un date

CREATE TABLE sobranteRestaurante (
	idSobranteRest INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	turnoAM FLOAT NOT NULL,
	turnoPM FLOAT NOT NULL,
);

CREATE TABLE sobranteTiki (
	idSobranteTiki INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	turnoAM FLOAT NOT NULL,
	turnoPM FLOAT NOT NULL,
);

CREATE TABLE VentaDiariaTiki (
	idVentaTiki INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	fecha DATE NOT NULL,
	turnoAM FLOAT NOT NULL,
	turnoPM FLOAT NOT NULL,
);

CREATE TABLE VentaDiariaRestaurante (
	idVentaTiki INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	fecha DATE NOT NULL,
	turnoAM FLOAT NOT NULL,
	turnoPM FLOAT NOT NULL,
);


--Pagina Licores--

CREATE TABLE Licor (
	idLicor INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	tipo FLOAT NOT NULL,
	nombre TEXT NOT NULL,
	prest TEXT NOT NULL,
	precio FLOAT NOT NULL,
);


CREATE TABLE ConsumoLicRestaurante (
	idConsumoLicRest INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idLicor INT NOT NULL,
	pedidos FLOAT NOT NULL,
	medida FLOAT NOT NULL,
	invInicial FLOAT NOT NULL,
	botella INT NOT NULL,
	trago FLOAT NOT NULL,
	ventas FLOAT NOT NULL,
	CONSTRAINT FK_ConsumoLicrestaurante_Licor FOREIGN KEY (idLicor) REFERENCES Licor(idLicor),
);


CREATE TABLE ConsumoLicTiki (
	idConsumoLicRest INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idLicor INT NOT NULL,
	pedidos FLOAT NOT NULL,
	medida FLOAT NOT NULL,
	invInicial FLOAT NOT NULL,
	botella INT NOT NULL,
	trago FLOAT NOT NULL,
	ventas FLOAT NOT NULL,
	CONSTRAINT FK_ConsumoLicTiki_Licor FOREIGN KEY (idLicor) REFERENCES Licor(idLicor),
);



--Insercicion de datos--
--Pagina Mermas--
INSERT INTO Producto VALUES ('ARROZ', 1586.5, 'BOL 1800', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('ARROZ SUSHI', 1870, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('ALAS', 3950, '', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('ATUN', 11000, 'K', 'MERMAS');
INSERT INTO Producto VALUES ('LOMITO ANGUS', 23500, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MAZA PIZZA', 989, '', 'MERMAS');
INSERT INTO Producto VALUES ('CARNE TORTA', 4945, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CAMARON PINKI 3135', 7500, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CAMARON COCTAIL', 13500, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CAMARON JUMBO', 18800, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MARISCOS MIXTOS', 7000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MARLIN BLANCO', 8800, '', 'MERMAS');
INSERT INTO Producto VALUES ('CALAMAR', 6500, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CORVINA PP', 9000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CORVINA REINA', 11000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('COSTILLA', 4706, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('FERTUCHINNI', 2024, '', 'MERMAS');
INSERT INTO Producto VALUES ('DORADO', 8000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('DEDOS DE QUESO', 39501529.555, '', 'MERMAS');
INSERT INTO Producto VALUES ('MEJILLONES', 9600, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('COLAS DE LANGOSTA', 27000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('LOMITO NOVILLO', 13000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('PARGO', 6700, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('FILET PARGO', 14000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('POLLO PECHUGA', 3950, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('POLLO FILET', 5850, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('QUESO', 4590, '', 'MERMAS');
INSERT INTO Producto VALUES ('QUESO BOCONCINI', 5902, '', 'MERMAS');
INSERT INTO Producto VALUES ('RIB EYE', 18918.92, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('SALMON', 13700, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('SUSHI', 1870, '', 'MERMAS');
INSERT INTO Producto VALUES ('TORTILLA TRIGO GRANDE', 3216, 'PAQ', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('JUMBO', 18800, '', 'MERMAS');
INSERT INTO Producto VALUES ('BISTEC', 6875, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('BISTEC CERDO', 4450, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('BISTEC HIGADO', 4611, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CARACOLITOS', 3550, '', 'MERMAS');
INSERT INTO Producto VALUES ('CANELONES', 3550, 'PAQ', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CARNE MOLIDA', 5805, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CARNE MOLIDA CERDO', 3561, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CAMARON 4150', 6200, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CHULETA', 4200, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CREMA DULCE', 4110, 'L', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CHOP SUEY', 5019, 'PAQ 860G', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('CHORIZO', 1100, 'PAQ 450', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('FETUCHINNI', 2024, 'PAQ 500G', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('FRIJOLES', 1350, 'BOL 800', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('FRIJOLE TIERNO', 1125, '', 'MERMAS VERDURAS');
INSERT INTO Producto VALUES ('GARBANZOS', 1006, 'U', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('HUEVOS', 2100, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('JAMON', 3035, 'PAQ', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('LOMITO RES', 13000, '', 'MERMAS');
INSERT INTO Producto VALUES ('LENTEJAS', 1400, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MACARELA', 5000, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MONDONGO', 4096, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MENUDOS', 2000, '', 'MERMAS');
INSERT INTO Producto VALUES ('MUSLO', 2800, '', 'MERMAS');
INSERT INTO Producto VALUES ('PAPAS FRITAS', 5842, '', 'MERMAS');
INSERT INTO Producto VALUES ('PATAS DE CERDO', 4112, '', 'MERMAS');
INSERT INTO Producto VALUES ('POSTA PECHO', 4950, '', 'MERMAS');
INSERT INTO Producto VALUES ('POSTA CON HUESO', 1668, '', 'MERMAS');
INSERT INTO Producto VALUES ('QUESO MOTZARELLA', 8003.15, 'BOL 1500', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('TIKIKENA', 4950, '', 'MERMAS');
INSERT INTO Producto VALUES ('TOCINETA', 12705, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('TORTILLAS', 1300, 'PAQ 10U', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('SALCHICHON', 2025, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('SALCHICHA DESAYUNO', 7954, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('SPAGUETTI', 1954, 'PAQ', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('VERDURAS', 50000, '', 'MERMAS');
INSERT INTO Producto VALUES ('GELATINA LAMINA', 550, '', 'MERMAS VERDURAS');
INSERT INTO Producto VALUES ('PASTA DE TOMATE', 630, '', 'MERMAS');
INSERT INTO Producto VALUES ('YOGURT', 1850, '', 'MERMAS, VERDURAS');
INSERT INTO Producto VALUES ('MIEL', 5621, '960G', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('LECHE CONDENSADA', 1190, 'U 395G', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('LECHE EVAPORADA', 929, 'U 315G', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE DE COCO', 40000, '', 'MERMAS');
INSERT INTO Producto VALUES ('COCO RALLADO', 9424, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('AZUCAR MORENO', 2200, '', 'MERMAS VERDURAS');
INSERT INTO Producto VALUES ('JUGO LIMON', 9800, '', 'MERMAS');
INSERT INTO Producto VALUES ('GELATINA', 500, '', 'MERMAS');
INSERT INTO Producto VALUES ('SALSA BBQ', 3195, 'GAL', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('JUGO NARANJA', 851, '', 'MERMAS');
INSERT INTO Producto VALUES ('CONSOME', 3000, '', 'MERMAS');
INSERT INTO Producto VALUES ('AGUACATE', 2772, 'K', 'VERDURAS MERMAS');
INSERT INTO Producto VALUES ('GUACAMOLE', 2521, 'CJ 12X453G', 'MERMAS');
INSERT INTO Producto VALUES ('POSTA CERDO', 4700, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('MARLIN BLANCO', 8800, 'K', 'MERMAS PEDIDOS');
INSERT INTO Producto VALUES ('VEGETALES Y FRUTA', 160000, '', 'MERMAS'); 

--Pagina Verduras--

INSERT INTO Producto VALUES ('ALBAHACA', 345, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('AJO PELADO', 3663, 'PAQ', 'VERDURAS');
INSERT INTO Producto VALUES ('APIO', 1399, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('ALFALFA', 850, '', 'VERDURAS');
INSERT INTO Producto VALUES ('AYOTE TIERNO', 631, '', 'VERDURAS');
INSERT INTO Producto VALUES ('BANANO', 39, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('BERENJENA', 550, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('BROCOLI', 1200, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CAMOTE', 792, '', 'VERDURAS');
INSERT INTO Producto VALUES ('CARAMBOLA', 650, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CAS', 1062, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CEBOLLA', 900, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CEBOLLA MORADA', 1150, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CEBOLLINO', 396, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('COLIFLOR', 950, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('CULANTRO', 190, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('CULANTRO COYOTE', 120, '', 'VERDURAS');
INSERT INTO Producto VALUES ('CHAYOTE', 380, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('CHILE AJI', 1361, '', 'VERDURAS');
INSERT INTO Producto VALUES ('CHILE DULCE', 277, 'UN', 'VERDURAS');
INSERT INTO Producto VALUES ('CHILE MUNDIAL', 1485, 'PAQ', 'VERDURAS');
INSERT INTO Producto VALUES ('CHILE PANAMEÑO', 2300, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('ELOTE DULCE', 1633, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('ENELDO', 310, '', 'VERDURAS');
INSERT INTO Producto VALUES ('ESPINACA', 398, 'BOL', 'VERDURAS');
INSERT INTO Producto VALUES ('ESPARRAGOS', 4500, '', 'VERDURAS');
INSERT INTO Producto VALUES ('FRESA', 2800, 'CJ', 'VERDURAS');
INSERT INTO Producto VALUES ('FLORES', 1374, '', 'VERDURAS');
INSERT INTO Producto VALUES ('HONGOS', 1950, 'CJ', 'VERDURAS');
INSERT INTO Producto VALUES ('HONGO PORTOBELLO', 2301, '', 'VERDURAS');
INSERT INTO Producto VALUES ('JENGIBRE', 1327, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('KIWI', 3097, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('LECHUGA ARRUGULA', 3539, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('LECHUGA USA', 275, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('LECHUGA ROMA', 275, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('LIMON MANDA', 80, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('LIMON MESINO', 180, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('JUGO GALON', 9802, '', 'VERDURAS');
INSERT INTO Producto VALUES ('MALANGA', 650, '', 'VERDURAS');
INSERT INTO Producto VALUES ('MANGO', 1300, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('MANZANA', 1231, 'BOL', 'VERDURAS');
INSERT INTO Producto VALUES ('MARACUYA', 1690, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('MELON', 650, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('MINI ZANAHORIA', 1239, 'BAND', 'VERDURAS');
INSERT INTO Producto VALUES ('MINI ZUQUINI', 1239, 'VAN', 'VERDURAS');
INSERT INTO Producto VALUES ('MORA', 569, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('NARANJA', 100, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('NARANJA IMPORT', 1770, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('NARANJILLA', 1584, '', 'VERDURAS');
INSERT INTO Producto VALUES ('FRUTA DE AMOR', 1327, 'CJ', 'VERDURAS');
INSERT INTO Producto VALUES ('OREGANO', 188, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('PASAS', 782, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('PAPA', 1390, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('PAPAYA', 544, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('PAPA SEMILLA', 1160, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('PEJIBALLE', 1980, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('PEPINO', 836, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('PERAS', 585, '', 'VERDURAS');
INSERT INTO Producto VALUES ('PEREJIL', 158, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('PIÑA', 841, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('PLATANO MADURO', 295, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('PLATANO VERDE', 282, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('RADICHO', 1300, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('REMOLACHA', 425, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('REPOLLO', 700, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('REPOLLO MORADO', 1683, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('ROMERO', 398, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('SALCHON PARRILLERA', 1683, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('SANDIA', 550, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('SALVIA', 354, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('TAMARINDO', 441, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('TIKISQUE', 1425, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('TOMATE', 1100, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('TOMATE CHERRY', 1089, 'PAQ', 'VERDURAS');
INSERT INTO Producto VALUES ('TOMATE PERA', 1485, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('TOMATE SEGUN', 1133, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('TOMILLO', 198, 'U', 'VERDURAS');
INSERT INTO Producto VALUES ('UVA VERDE', 4778, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('VAINICA', 975, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('VAINICA BB', 1283, 'BAND', 'VERDURAS');
INSERT INTO Producto VALUES ('HIERBA BUENA', 371, 'PAQ', 'VERDURAS');
INSERT INTO Producto VALUES ('YUCA', 650, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('ZUQUINI', 643, 'K', 'VERDURAS');
INSERT INTO Producto VALUES ('ZANAHORIA', 495, 'K', 'VERDURAS');

--Pagina Pedidos--
INSERT INTO Producto VALUES ('ACEITE', 18975, 'PCH 17L', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE AEROSOL', 7129, 'U 650', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE AJONJOLI', 20352, 'L 17', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE EEVV', 22795, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE FREIDOR', 21780, 'PCH 17L', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE OLIVA', 15575, 'U 5L', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITE PICANTE', 3824, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITUNA KALAMATA', 20959, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITUNA NEGRA', 7128, 'K 1.5', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITUNA RELLENA', 2075, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACEITUNA VERDE', 4732, 'ML 975', 'PEDIDOS');
INSERT INTO Producto VALUES ('ACHIOTE', 4123, 'U 850G', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO BLUE CHESSE', 18324, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO CEASAR', 0, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO ITALIANO', 10641, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO RANCH', 9283, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO VINAGRETA', 3395, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('ADEREZO MIL ISLAS', 12360, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('ALAS DE POLLO', 3950, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('AJONJOLI BLANCO', 7487.70, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('AJONJOLI NEGRO', 6977.86, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('ALCACHOFAS', 1961, 'U 390G', 'PEDIDOS');
INSERT INTO Producto VALUES ('ALCAPARRA', 5127, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('ALMENDRA PELADA', 10850, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('ANCHOAS', 1600, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('ARROZ JASMIN', 4190, 'G 956', 'PEDIDOS');
INSERT INTO Producto VALUES ('AZUCAR', 1512, 'BOL 2000G', 'PEDIDOS');
INSERT INTO Producto VALUES ('BASE TOMATE KNORR', 4786, 'U 500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('BATER', 2272, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CAMARON FIDEL', 7000, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('CANELA EN POLVO', 9118, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CANELA ROLLO', 3969, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CARNE MOLIDA ECONOMICA', 4100, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('CARNE PARA TORTAS', 18975, 'PCH', 'PEDIDOS');
INSERT INTO Producto VALUES ('CARNE MANO PIEDRA', 6225, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('CHANTILLI', 2202, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CHERRYES', 13922, 'GAL 3780G', 'PEDIDOS');
INSERT INTO Producto VALUES ('CHILE EN ESCAMAS', 2779, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('CHIPOTLE', 2198, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CHULETA ESPECIAL', 5247, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('COCOA EN POLVO', 2953, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('COMINO', 7244, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('CONSOME MARISCOS', 9404, 'GAL 3780G', 'PEDIDOS');
INSERT INTO Producto VALUES ('CONSOME POLLO', 14101, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('CORDERO', 24350, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('COSTILLA BABY RACK', 3454, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('CURCUMA', 0, '', 'PEDIDOS');
INSERT INTO Producto VALUES ('CURRY', 4110, '', 'PEDIDOS');
INSERT INTO Producto VALUES ('CURRY ROJOPASTA', 2880, 'U 195G', 'PEDIDOS');
INSERT INTO Producto VALUES ('EDAMAME', 2403, 'LIBRA', 'PEDIDOS');
INSERT INTO Producto VALUES ('ENSALADA DE ALGAS', 27795, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('ESCARGOT', 3253, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('GALLETA MARIA', 0, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('HARINA', 1838, 'BUL 10X1', 'PEDIDOS');
INSERT INTO Producto VALUES ('HARINA', 2689, 'BUL 4X2.5', 'PEDIDOS');
INSERT INTO Producto VALUES ('HASH BORWN', 5130, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('HELADO', 19956, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('HOJAS DE LAUREL', 2432, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('HOJALDRE', 1976, '500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('HONGOS PORCINI', 30130, '450G', 'PEDIDOS');
INSERT INTO Producto VALUES ('HONGOS REBANADOS', 4546, 'K 2.84 ', 'PEDIDOS');
INSERT INTO Producto VALUES ('JALAPENO', 668, '240G', 'PEDIDOS');
INSERT INTO Producto VALUES ('JALAPENO POPER', 11270, 'CAJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('JAMON DE PAVO', 2405, 'PAQ 250G', 'PEDIDOS');
INSERT INTO Producto VALUES ('JAMOS SERRANO', 22370, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('JENGIBRE ROSADO', 44846, 'CUBETA', 'PEDIDOS');
INSERT INTO Producto VALUES ('KETCHUP', 4242, 'GAL 3780', 'PEDIDOS');
INSERT INTO Producto VALUES ('KETCHUP PAQUETE', 22404, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('KETCHUP SQUESE', 1543, 'U 560G', 'PEDIDOS');
INSERT INTO Producto VALUES ('LECHE COCO', 980, 'U 414G', 'PEDIDOS');
INSERT INTO Producto VALUES ('MACADAMIA', 24983, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAICENA', 5579, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAIZ DULCE', 649, '180G', 'PEDIDOS');
INSERT INTO Producto VALUES ('MANI PICADO', 3926, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('MANTECA', 30744, 'CJ 25K', 'PEDIDOS');
INSERT INTO Producto VALUES ('MANTEQUILLA 2PINOS', 1130, '115G', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAPLE', 8597, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('MARGARINA', 15446, 'CJ 12.5K', 'PEDIDOS');
INSERT INTO Producto VALUES ('MASA PIZZA', 989, 'CJ 12X535', 'PEDIDOS');
INSERT INTO Producto VALUES ('MASAGO', 29927, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAYONESA', 7930.11, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAYONESA PAQUETE', 4396, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('MAYONESA SQUESE', 2629, 'U  562G', 'PEDIDOS');
INSERT INTO Producto VALUES ('MEZCLA PANCAKE', 5150, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('MEZCLA TEMPURA', 26625, 'CJ 14K', 'PEDIDOS');
INSERT INTO Producto VALUES ('MINI MARGARINA', 33760, 'CJ 2320 U', 'PEDIDOS');
INSERT INTO Producto VALUES ('MINI MERMELADAS', 15679, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('MOSTAZA', 9287, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('MOSTAZA DIJON', 2617, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('MOSTAZA SQUESE', 1686.16, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('MOSTAZA PAQUETE', 8212, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('NATILLA', 846.60, '500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('NUEZ NOGAL', 9251, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('PALILLOS DE QUESO', 15295.55, 'BOL 1800G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PALMITO', 2544, 'U 800G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN CENA', 5887, 'CJ 50U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN CHAPATA', 12377, 'CAJX11', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN CUADRADO', 1460, 'BOL', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN ENGLISH MUFFINS', 2695, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN HAMBURGUESA', 3970, 'BOL 20U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN INTEGRAL', 1215, 'BOL', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAN MOLIDO', 3742, 'PAQ 2000G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAPA GAJO', 6387, 'BOL 2268G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAPA KRISPY', 5842, 'BOL 2500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAPEL ALGAS', 6388.10, 'PAQ 50U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAPRIKA', 4232, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAVO', 33395, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PAVO RELLENO', 138645, 'TOTAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('PEPERONI', 12460, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('PEPINILLO', 7501, 'GAL 3780', 'PEDIDOS');
INSERT INTO Producto VALUES ('PETTIT POIS', 58, 'U 576G', 'PEDIDOS');
INSERT INTO Producto VALUES ('PEZUNA DE CERDO', 1661, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('PIMIENTA CAYENA', 0, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PIMIENTA NEGRA', 11109, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('PIMIENTA GRANO', 10440, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('PIMIENTA VERDE', 10293, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('PISTACHO PELADO', 24453, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('POLLO MENUDOS', 2000, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('POLLO MUSLO', 4350, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('POLLO ENTERO', 3850, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('POSTA DE CERDO', 4700, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('POSTA HUESO CERDO', 1500, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('POSTA HUESO RES', 1668, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('POSTA PECHO RES', 4950, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('PULPA DE TAMARINDO', 5513, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('PULPO', 10000, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO BLANCO', 3600, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO CHEDAR', 11482, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO CHEDAR DERRETIDO', 3527.82, 'L', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO CREMA', 16767, 'GAL 3780G', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO FETA', 6941, '500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO MOZARELA FRESCO', 5786.80, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO PARMESANO CUNA',10800, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO PARMESANO RAYADO', 13621, '500G', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO PIZZA', 10290, 'PAQ 500U', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO PROVOLONE', 6077, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO REBANADO', 3737, 'PAQ 640G', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO MOZARELA FRESCO', 5786.80, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('RABANO PICANTE', 6060, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAL', 450, 'U 1000G', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAL PIMIENTA', 2176.34, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO', 5786, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA A1', 2395, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA BUFALO', 8357.62, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA CHILI THAI', 8285, '2000G', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA CHINA', 3945, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA DEMIGLAS', 16060, 'CAJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA HOLANDESA', 1319.69, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA LIZANO UINDAD', 7626, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA LIZANO BOTELLA', 575, 'BOT 135', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA DE OSTIONES', 8379.83, 'L 4.85', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA PERRY GALON', 11725, 'GAL 3780', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA PERRY BOTELLA', 1830, 'BOT', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA PESCADO', 0, 'BOT', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA PIZZA', 5897, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA SOYA LIGTH', 8147, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA SOYA', 15030, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA SRIRACHA', 3153, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA SUSHI', 17347, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SALSA TERIYAKI', 16168, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAZONADOR CAJUN', 7180, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAZONADOR COMPLETO', 7196, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAZONADOR MONTREAL', 7196, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SAZONADOR DE POLLO', 5191, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SEMILLAS DE MARANON', 11595, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('SOPA', 4352, 'CJ 12X60G', 'PEDIDOS');
INSERT INTO Producto VALUES ('SURIME', 5605, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('TABASCO', 583, 'BOT 64G', 'PEDIDOS');
INSERT INTO Producto VALUES ('TE MANZANILLA', 3490, 'CAJ 100U', 'PEDIDOS');
INSERT INTO Producto VALUES ('TE NEGRO', 3795, 'CJ', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOCINO CANADIENSE', 9500, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOCINO PREFORMADO', 82097, 'CJ 6.8', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOPIN CARAMELO', 1720, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOPIN CHOCOLATE', 2233, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOPIN DE FRESA', 1720, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOPIN KIWI', 2304, 'U', 'PEDIDOS');
INSERT INTO Producto VALUES ('TORTILLA ESPINACA', 3621, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('TORTILLA TOMATE', 3410, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO', 5786, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('TORTILLA TRIGO PEQUENA', 3654, 'PAQ', 'PEDIDOS');
INSERT INTO Producto VALUES ('VAINOL', 17513, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('VINAGRE', 2271, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('QUESO', 13469, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('VINAGRE DE ARROZ', 21840, 'PCH 20L', 'PEDIDOS');
INSERT INTO Producto VALUES ('VINAGRE MANZANA', 7335, 'GAL', 'PEDIDOS');
INSERT INTO Producto VALUES ('VINAGRE MIRIN', 55222, 'PICHINGA', 'PEDIDOS');
INSERT INTO Producto VALUES ('WASABI', 9529, 'K', 'PEDIDOS');
INSERT INTO Producto VALUES ('TOMAHAWK', 15285, 'K', 'PEDIDOS');


INSERT INTO PlatosDevueltos VALUES ('ARROZ CON POLLO', 1827.53, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('ALAS DE POLLO', 4268.98, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('COCTAIL', 2678.86, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('FAJITAS DE CARNE', 5758.54, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('FILET MIGNON', 7756.09, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('PAPA KRISPY', 342.6, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('PIZZA', 2500, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('POKE SALMON', 4360.87, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('QUESADILLA POLLO', 3513.68, '', 'MERMAS');
INSERT INTO PlatosDevueltos VALUES ('THAI CEVICHE', 3427.61, '', 'MERMAS');
